debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    org.example.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
#    url: jdbc:mysql://localhost:3307/board   # 여기는 mysql 방식
#    username: boards
#    password: "@cce7717"
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/board   #postgresql
    username: chris
    password: "1234"



  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false #???? false h2 db ?? ??? true? ??
  sql.init.mode: always
  data.rest: #dataRepository?  dependencies? ?? ?? ?? ?? ???
    base-path: /api #??? http://localhost:8080/api ?????? ?????? /api? ???? ???
    detection-strategy: annotated  #annotated? ????? ??? ?? ?? ???
  thymeleaf3:
    decoupled-logic: true








  #data.rest:
    # base-path: /api
    #detection-strategy: annotated

---

#?? db ???? ?? ????
#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none